
export function cleanResumeText(rawText: string): string {
  // 1. Remove obvious headers/footers (regex for common patterns)
  let text = rawText.replace(/(Page \d+ of \d+)|(Generated by.*)/gi, '');
  
  // 2. Remove multiple newlines/whitespace
  text = text.replace(/\n\s*\n/g, '\n').trim();
  
  return text;
}

export function heuristicExtract(text: string) {
  const emailRegex = /([a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+\.[a-zA-Z0-9_-]+)/;
  const phoneRegex = /(\+?\d{1,4}?[-.\s]?\(?\d{1,3}?\)?[-.\s]?\d{1,4}[-.\s]?\d{1,4}[-.\s]?\d{1,9})/;
  
  const emailMatch = text.match(emailRegex);
  const phoneMatch = text.match(phoneRegex);
  
  // Simple heuristics for a name (often first or last line)
  const lines = text.split('\n');
  const name = lines[0].length < 50 ? lines[0] : 'Unknown';
  
  return {
    name,
    email: emailMatch ? emailMatch[1] : null,
    phone: phoneMatch ? phoneMatch[1] : null,
  };
}
